### ISSUE TITLE
Correction to two bibliographic entries. 

### ISSUE THREAD

**Issue by phisaz** [Derek-Jones/ESEUR-book#14]
Kind request of correction to the following bibliographic entries. Many thanks! 

Regarding "Antonio Vetroò, Rupert Dürre, Marco Conoscenti, Daniel Méndez Fernández, and Magne Jørgensen. Combining data analytics with team feedback to improve the estimation process in agile software development. Foundations of Computing and Decision Sciences, 43(4):305–334,   December 2018.”

1. Antonio Vetroò —> Antonio Vetrò
2. Link article to the publisher site: https://doi.org/10.1515/fcds-2018-0016 
3. Link article to open version in the institutional repository: https://iris.polito.it/retrieve/handle/11583/2722515/224876/2018-fcds-ffc.pdf 

Regarding  “Marco Conoscenti, Veronika Besner, Antonio Vetrò, and Daniel Méndez Fernández. Combining data analytics and developers feedback for identifying reasons of inaccurate estimations in agile software development. The Journal of Systems and Software, 156:126–135, October 2019.”  

1. Link article to the publisher site: https://doi.org/10.1016/j.jss.2019.06.075 
2. Link article to open version in the institutional repository: https://iris.polito.it/retrieve/handle/11583/2747492/266076/elsarticle-template.pdf

**Comment by Derek-Jones** [comment]
Fixed: Antonio Vetroò —> Antonio Vetrò
See: http://knosof.co.uk/ESEUR/ESEUR-references.html

Also fixed in citation with R code.

Thanks for providing articles links.  I expect many readers to be professional software developers, who will not have free access to papers on publishers sites.  The Google search will hopefully link to pdf that they can download.

**Comment by phisaz** [comment]
Many thanks! 

About links: the link nr.2 that I provided from each paper points directly to the openly accessible version: could you put that ?
For one of them there is an embargo, but it is expiring in few months.

A.

**Comment by Derek-Jones** [comment]
I clicked on both links in: http://knosof.co.uk/ESEUR/ESEUR-references.html
and in both cases pdf versions of the papers appeared as the first link found by Google.  No problem with embargo :-)

**Comment by phisaz** [comment]
Ok ! :-D thanks
A.
