### ISSUE TITLE
uncloned on p9

### ISSUE THREAD

**Issue by bazzargh** [Derek-Jones/ESEUR-book#15]
```
In practice, research
has shown that the opposite is true, clones are less likely to contain faults than
’uncloned\’ source.
```

closing quote before 'uncloned' instead of opening quote, and backslash after

**Comment by Derek-Jones** [comment]
Thanks, fixed.

Asciidoc requires escaping the first ' (so the word does not get treated as being in italics), which is very confusing to those of us used to escaping all or none.

**Comment by Derek-Jones** [comment]
Also fixed two occurrences in Human cognition chapter.
