### ISSUE TITLE
Phone readable publishing format.

### ISSUE THREAD

**Issue by SoftwareApe** [Derek-Jones/ESEUR-book#16]
Thank you for providing this book.

I'm not sure how you're publishing the book, but given the fact that many people always have their phone on hand PDF is not ideal. Instead some ebook format which allows reflowing the text would be helpful.

**Comment by Derek-Jones** [comment]
The amount of special case formatting in the raw text (various scripts were written to process the intermediate output before being passed to LuaLatex) means it would be a lot of work to switch to another output format.

I am thinking of producing a plots only ebook is various formats, perhaps with optional R code.  Would that be interesting?

**Comment by SoftwareApe** [comment]
Thanks for replying. I'm not sure what a plots only ebook would mean, since what I find hard is reading hundreds of pages scrolling left to right for the text. I do understand if it's difficult to have multiple output formats.

**Comment by woile** [comment]
Same as SoftwareApe, it's a  pitty, but I'll try reading from the PDF. 
I'm also not sure what a plot only ebook is.

Thanks again for the work! Highly appreciated!

**Comment by Derek-Jones** [comment]
A plots only ebook would just contain the plots that appear in the outside margin.

My assumption is that people would be interested in finding data associated with an issue they have.  Being able to look at the plots, or search via meaningful captions (some work needed for this) would be useful (he said grasping for straws...)?

**Comment by woile** [comment]
hahaha no worries! I think a pdf would actually be useful for that. The kindle ui and refresh rates are quite slow, so I wouldn't use it to search.

**Comment by Derek-Jones** [comment]
Would a pdf with shorter lines help?

It would probably be relatively easy to generate a more narrow width device friendly pdf.

**Comment by woile** [comment]
I think so, it would be great.

**Comment by Derek-Jones** [comment]
Just generated a reduced text width pdf.  Easy to do.  But will take some time to double check for serious layout problems.

I cannot find any suggested guides for generating pdfs for mobile devices.

How many characters per line might be best?

**Comment by Derek-Jones** [comment]
Checkout the [experimental mobile friendly pdf](http://knosof.co.uk/ESEUR/ESEUR-mobile.pdf).

Some of the formatting is off, but is it easier to read?

**Comment by bbigras** [comment]
I came here from #17. Would an epub format be possible? It could be great with ebook readers like the kindle.

**Comment by Derek-Jones** [comment]
Generating an epub formatted file would be a lot of work.

[Reflowable](https://en.wikipedia.org/wiki/Reflowable_document) pdfs are one answer, and there are readers such as [xodo](https://www.xodo.com/) and [Librera](https://librera.mobi/) that claim to do it automatically (have not tried).

I'm reading about embedding tags in the pdf to give reflow hints, but I have not seen any packages to help out.

Pointers welcome.

Have you checked out the experimental mobile pdf version?

**Comment by woile** [comment]
Hey Derek I was able to test it, and I didn't find it useful. I think what would help is a smaller page. With the mobile pdf I found myself scrolling all around the same page.

**Comment by Derek-Jones** [comment]
Wolle,

I have uploaded a new version.  The paper width now matches the text+plot width, so margins are minimal, but text width is the same.

The text is readable on my old Android phone (screen 1920x1080 px, width 69.8 mm or 2.75 in).

With text+plots you are either going to have to scroll horizontally or vertically.

The table layout could be better, but that is a generic problem to both pdf layouts.

**Comment by bbigras** [comment]
> Have you checked out the experimental mobile pdf version?

I'm going to give it a try. Maybe the kindle will read the pdf just fine or maybe I could try to convert it with calibre. Thanks!

**Comment by bbigras** [comment]
![Screenshot_20201114-202550](https://user-images.githubusercontent.com/24027/99160726-0b476b80-26b8-11eb-9053-70f9baa51d0a.png)

This is how it looks on Kindle for Android.

**Comment by Derek-Jones** [comment]
Hey, that looks good to me, but then I am looking at it on a large screen.

Is it readable when looking at the device?

Do the color plots look ok?

**Comment by bbigras** [comment]
> Is it readable when looking at the device?

It's a bit tiny but I can zoom and scroll. So I'm guessing it's the best we can get. Also, I didn't realize there were some plots in the margin.

The plots look fine:
![image](https://user-images.githubusercontent.com/24027/99848094-121b2600-2b71-11eb-8861-e6e3225c4e61.png)

**Comment by Derek-Jones** [comment]
What is the width of your screen?

Mine is 1920x1080 px, width 69.8 mm or 2.75 in, and the text looks (but not sure I would want to read it for very long).

**Comment by bbigras** [comment]
It's a Pixel 2: "5-inch (130 mm) 16:9 1080p (1920 × 1080) AMOLED display panel with a pixel density of 441 pp"

It might be readable without zooming but it's a bit tiny. It looks like this:

![image](https://user-images.githubusercontent.com/24027/99851947-eb142280-2b77-11eb-9ba1-f156a16dd96a.png)

while a normal book looks like:

![image](https://user-images.githubusercontent.com/24027/99852094-2c0c3700-2b78-11eb-833e-32f749337694.png)

**Comment by Derek-Jones** [comment]
I had assumed that people would not have the text and plots on the screen at the same time.  Otherwise the amount of text per line would be a word or two.
