### ISSUE TITLE
Is the ISBN number in the PDF invalid?

### ISSUE THREAD

**Issue by bgianfo** [Derek-Jones/ESEUR-book#18]
I imported [this PDF](http://knosof.co.uk/ESEUR/ESEUR.pdf) into my reference manager ([paperpile](https://paperpile.com/)) and it's unable to auto populate the information once I associated the ISBN.

This lead me to check and it looks like the ISBN in the PDF seems to be invalid/unknown?

> ISBN: 978-1-8382913-0-3
> Publisher: Knowledge Software, Ltd
> Released: November 8, 2020

Examples:
- https://us.nicebooks.com/search/isbn?isbn=978-1-8382913-0-3
- https://isbnsearch.org/isbn/9781838291303

**Comment by Derek-Jones** [comment]
Thanks for prompting me about the ISBN number.

I purchased the numbers last Friday and have yet to fill out the form to associate this number with the pdf.

**Comment by Derek-Jones** [comment]
Just registered my details at a different site than the one that sold me the isbns, and received a confirmation that they have received my details.

Now I have to wait 5 to 10 working days.  Ah, the luxury of not having any competition when selling isbns.

**Comment by Derek-Jones** [comment]
ISBN now registered and working.  The BIC subcode is incorrect, and I have notified Nielsen about the changed needed.
