### ISSUE TITLE
Excess backslash after the word "uncloned"

### ISSUE THREAD

**Issue by david-a-wheeler** [Derek-Jones/ESEUR-book#19]
I've only started, but I'm enjoying your book!! It's a *delight* to see someone care about actual evidence.

I intend to alert you to various nits. Here's one.

On page 9:

> clones are less likely to contain faults than ’uncloned\’ source.

Remove the excess backslash after the word "uncloned".

**Comment by Derek-Jones** [comment]
I'm also keen to hear about things larger than a nit :-)

The material is somewhat disjoint; that is the nature of only writing the data, when lots of data is not available.

Ah, the joy of using a text processing system where only the first ' of a pair has to be escaped.

Done.

**Comment by david-a-wheeler** [comment]
No problem! I plan to send other complaints large & small, but I really appreciate the work you've put into this.
