### ISSUE TITLE
Note "average" is another word for "mean"

### ISSUE THREAD

**Issue by david-a-wheeler** [Derek-Jones/ESEUR-book#20]
Page 16 provides an introduction to statistical symbols and notation, which suggests that the intended reader isn't already familiar with them. In that case, the definition of mu (mean) should be modified:

> • m (mu), commonly denotes the mean value; calculated by R’s mean function,

This should mention the word "average"; many people won't know what a mean is, but "average" is a word they'll know. E.g.:

> • m (mu), commonly denotes the mean (aka average) value; calculated by R’s mean function,

I know this & you know this, but your readers might not. Technically there are many means and averages, but if you don't say otherwise, it's the arithmetic mean (aka arithmetic average), so you don't need to delve into that technicality here.

**Comment by Derek-Jones** [comment]
Good point.  The text does use average in places.

In other cases I highlight other terms that are sometimes used.

Done.
