### ISSUE TITLE
Fuzzers are also used to find vulnerabilities and that isn't clear in the discussion on faults

### ISSUE THREAD

**Issue by david-a-wheeler** [Derek-Jones/ESEUR-book#23]
Section 6.6 asks this question:

> To what extent are fault experiences generated by fuzzers representative of faults experienced
by users of the software?

That *is* an interesting question, but necessarily incomplete. Often fuzzers are used not to detect "generic" faults', but to fine security vulnerabilities. Thus, there are *two* relevant groups:

* users of the software - in which case, what is the likelihood that a user will be impacted by the fault?
* attackers - in which case, what is the likelihood that an attacker will find the vulnerability? In the latter case, since the attacker could typically also run the same tool, or a tool that works in a similar way, we typically presume that an attacker will also eventually find it (so we approximate this as 100%).

Something about this other use case of fuzzers should be noted, because I think often fuzzers are used to find *security vulnerabilities*, not faults in general, which is a difficult kind of use.

**Comment by Derek-Jones** [comment]
Fuzzers are discussed in various contexts, e.g., this one and others where they can be used to estimate the number of remaining fault experiences.  The use case of not caring whether fuzzers are representative of user usage deserves a mention, but I'm wondering how a broader connection of dots might be made around fuzzer usage.

I need to check the various analysis of fuzzing data.

**Comment by Derek-Jones** [comment]
Not wanting to get into reworking the material, I have gone with adding a footnote:
_When searching for security vulnerabilities, the fault experiences discovered by fuzzing are only required to depend on input that a user might be induced to produce._

**Comment by david-a-wheeler** [comment]
Adding a short footnote is great, but the footnote's wrong. Instead of:

> When searching for security vulnerabilities, the fault experiences discovered by fuzzing are only required to depend on input that a user might be induced to produce.

It should be:

> When searching for security vulnerabilities, the fault experiences discovered by fuzzing are only required to depend on input that an attacker could generate.

**Comment by Derek-Jones** [comment]
attacker vs. user

Are we looking at this from two perspectives?  An academic perspective interesting in attacking to generate fault experiences, a commercial perspective where the focus is on what the user could possibly input.

Now, I don't think it's always possible to figure out whether the user could possibly type some particular input, and people play safe by assuming it's possible.

When fuzzing source, anything the fuzzer can generate the user could generate.  But when fuzzing binaries this is not the case.

**Comment by david-a-wheeler** [comment]
There are two different perspectives, "user" and "attacker".

The current text says: "input that a user might be induced to produce". The input distribution of a non-attacking user is different from an attacker.  Yet the current text says:

> When searching for security vulnerabilities, the fault experiences discovered by fuzzing are only required to depend on input that a user might be induced to produce.

Many people will assume that "user" means "non-attacker". But the input distribution of a non-attacker is irrelevant if you are concerned about security vulnerabilities.

I assume that's not what you mean. So I suggest saying instead:

> When searching for security vulnerabilities, the fault experiences discovered by fuzzing are only required to depend on input that an attacker could generate.

**Comment by Derek-Jones** [comment]
Yes, the issue is "user produced".  How the input was produce does not matter.

How about:
_When searching for security vulnerabilities, the fault experiences discovered by fuzzing are only required to depend on input that a user might be induced to feed into a program._

The case I'm trying to exclude is where program_X sits at the end of a pipeline, and some basic checks are performed before the user input reaches program_X.

Unless the user bypasses the pipeline, the earlier checks may catch some inputs that would otherwise be a security vulnerability.

**Comment by david-a-wheeler** [comment]
> The case I'm trying to exclude is where program_X sits at the end of a pipeline, and some basic checks are performed before the user input reaches program_X.

Sure. In that case, an attacker cannot induce things that won't pass the checks.

The fundamental problem is that:

> user might be induced

isn't relevant. "User" and "attacker"are not synonymous, nor necessarily either a subset of the other. I'd replace that with:

> attacker could induce

**Comment by Derek-Jones** [comment]
"User" and "attacker" are not synonymous: I agree.

"attacker could induce" is better because there might not be a user as such.
