### ISSUE TITLE
Non-7-bit characters in bibliography

### ISSUE THREAD

**Issue by gvwilson** [Derek-Jones/ESEUR-book#3]
The HTML version of the bibliography has some markers for mis-interpreted characters (screenshots). I think this is because BibTeX only handles 7-bit (ASCII) characters correctly; all other characters have to be represented using escape sequences.

![screen shot 2018-05-15 at 7 33 01 am](https://user-images.githubusercontent.com/911566/40054556-3cd370de-5813-11e8-897b-fbcc83093ce4.png)
![screen shot 2018-05-15 at 7 35 07 am](https://user-images.githubusercontent.com/911566/40054577-4dd0a80c-5813-11e8-903d-d78dff2e1130.png)

**Comment by Derek-Jones** [comment]
Removed the two non-printing characters in the original bibtex file.

Thanks for the screen shots, very useful.

The updated HTML file has been uploaded.

**Comment by Derek-Jones** [comment]
Found and fixed three more.
