### ISSUE TITLE
link to NASA ADA FORTRAN broken

### ISSUE THREAD

**Issue by timothytsai** [Derek-Jones/ESEUR-book#4]
link to https://github.com/Derek-Jones/ESEUR-code-data/blob/master/projects/nasa-ada-fortran.R on page 153 links to https://github.com/Derek-Jones/ESEUR-code-data/blob/master/projects/nasa-%7B%7Dada-%7B%7Dfortran.R instead of the former.

same issue for links on page 171.

**Comment by Derek-Jones** [comment]
This issue applies to any link to code, outside of  a figure, that contains a hyphen character.

Fixed.  Will wait a day or two to see if anything else gets reported, before posting an updated pdf.

**Comment by Derek-Jones** [comment]
Fix pushed, along with a couple of other fixes.
