### ISSUE TITLE
Prining?

### ISSUE THREAD

**Issue by Sileadim** [Derek-Jones/ESEUR-book#5]
On page 28 of v 0.14.0, in the figure about different memory systems it says "Prining &
perceptual learning". I could not find "prining" as a thing. MIN the OG paper it says "Priming" so likely a typo.

**Comment by Derek-Jones** [comment]
Yes, it should be "priming".  Fixed.

This figure is one of the few that is not generated using R, so was not included in the spell checking process.  Will fix by generating it in R.
